use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let pjproject_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("pjproject");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Build pjproject from source if not already built
    if !is_built(&pjproject_dir) {
        configure(&pjproject_dir);
        make(&pjproject_dir);
    }

    // Discover the target name used in library filenames (e.g. "x86_64-unknown-linux-gnu")
    let target_name = discover_target_name(&pjproject_dir);

    // Emit linker search paths
    let lib_dirs = [
        pjproject_dir.join("pjsip/lib"),
        pjproject_dir.join("pjmedia/lib"),
        pjproject_dir.join("pjnath/lib"),
        pjproject_dir.join("pjlib-util/lib"),
        pjproject_dir.join("pjlib/lib"),
        pjproject_dir.join("third_party/lib"),
    ];

    for dir in &lib_dirs {
        println!("cargo:rustc-link-search=native={}", dir.display());
    }

    // Link pjsip libraries (order matters for static linking — dependents first)
    let pj_libs = [
        "pjsua",
        "pjsip-ua",
        "pjsip-simple",
        "pjsip",
        "pjmedia-codec",
        "pjmedia",
        "pjmedia-audiodev",
        "pjnath",
        "pjlib-util",
        "pj",
    ];

    for lib in &pj_libs {
        println!("cargo:rustc-link-lib=static={}-{}", lib, target_name);
    }

    // Third-party libraries bundled with pjproject
    let third_party_libs = [
        "srtp",
        "resample",
        "gsmcodec",
        "speex",
        "ilbccodec",
        "g7221codec",
        "webrtc",
    ];

    for lib in &third_party_libs {
        let lib_name = format!("lib{}-{}.a", lib, target_name);
        if pjproject_dir
            .join("third_party/lib")
            .join(&lib_name)
            .exists()
        {
            println!("cargo:rustc-link-lib=static={}-{}", lib, target_name);
        }
    }

    // System libraries that pjproject depends on
    println!("cargo:rustc-link-lib=ssl");
    println!("cargo:rustc-link-lib=crypto");
    println!("cargo:rustc-link-lib=uuid");
    println!("cargo:rustc-link-lib=m");
    println!("cargo:rustc-link-lib=pthread");
    println!("cargo:rustc-link-lib=asound");

    // Check if opus was found during configure
    if pjproject_dir
        .join("third_party/lib")
        .join(format!("libopus-{}.a", target_name))
        .exists()
    {
        println!("cargo:rustc-link-lib=static=opus-{}", target_name);
    } else {
        // Link system opus if pjproject didn't bundle it
        println!("cargo:rustc-link-lib=opus");
    }

    // Generate bindings with bindgen
    let include_dirs = [
        pjproject_dir.join("pjsip/include"),
        pjproject_dir.join("pjmedia/include"),
        pjproject_dir.join("pjnath/include"),
        pjproject_dir.join("pjlib-util/include"),
        pjproject_dir.join("pjlib/include"),
    ];

    let mut builder = bindgen::Builder::default()
        .header(
            PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
                .join("wrapper.h")
                .to_string_lossy()
                .into_owned(),
        )
        .allowlist_function("pjsua_.*")
        .allowlist_function("pjmedia_.*")
        .allowlist_function("pjsip_.*")
        .allowlist_function("pj_.*")
        .allowlist_type("pjsua_.*")
        .allowlist_type("pjmedia_.*")
        .allowlist_type("pjsip_.*")
        .allowlist_type("pj_.*")
        .allowlist_var("PJSUA_.*")
        .allowlist_var("PJSIP_.*")
        .allowlist_var("PJMEDIA_.*")
        .allowlist_var("PJ_.*")
        .derive_debug(true)
        .derive_default(true)
        .detect_include_paths(true)
        .clang_arg("-xc")
        .clang_args(gcc_system_include_paths());

    if let Ok(target) = env::var("TARGET") {
        builder = builder.clang_arg(format!("--target={target}"));
    }

    for define in pj_build_defines(&pjproject_dir) {
        builder = builder.clang_arg(define);
    }

    for dir in &include_dirs {
        builder = builder.clang_arg(format!("-I{}", dir.display()));
    }

    // Include the generated config header
    let config_site = pjproject_dir.join("pjlib/include/pj/config_site.h");
    if config_site.exists() {
        builder = builder.clang_arg(format!(
            "-I{}",
            pjproject_dir.join("pjlib/include").display()
        ));
    }

    let bindings = builder
        .generate()
        .expect("Failed to generate pjsip bindings");

    bindings
        .write_to_file(out_dir.join("bindings.rs"))
        .expect("Failed to write bindings");

    // Rerun if pjproject source changes
    println!("cargo:rerun-if-changed=wrapper.h");
    println!("cargo:rerun-if-changed=pjproject");
}

fn is_built(pjproject_dir: &Path) -> bool {
    // Check if build.mak exists (generated by configure) and if libraries exist
    let build_mak = pjproject_dir.join("build.mak");
    if !build_mak.exists() {
        return false;
    }

    // Check for at least one output library
    let lib_dir = pjproject_dir.join("pjlib/lib");
    if !lib_dir.exists() {
        return false;
    }

    // Look for any .a file in the lib directory
    if let Ok(entries) = std::fs::read_dir(&lib_dir) {
        for entry in entries.flatten() {
            if entry.path().extension().is_some_and(|ext| ext == "a") {
                return true;
            }
        }
    }

    false
}

fn configure(pjproject_dir: &Path) {
    // Create minimal config_site.h
    let config_site_path = pjproject_dir.join("pjlib/include/pj/config_site.h");
    std::fs::write(
        &config_site_path,
        "/* Auto-generated by build.rs */\n\
         #define PJ_HAS_SSL_SOCK 1\n\
         #define PJMEDIA_HAS_VIDEO 0\n",
    )
    .expect("Failed to write config_site.h");

    let status = Command::new("./configure")
        .current_dir(pjproject_dir)
        // Disable all video-related features
        .arg("--disable-video")
        .arg("--disable-v4l2")
        .arg("--disable-ffmpeg")
        .arg("--disable-openh264")
        .arg("--disable-vpx")
        .arg("--disable-sdl")
        .arg("--disable-libyuv")
        // Disable unnecessary features to reduce attack surface
        .arg("--disable-libwebrtc")
        .arg("--disable-pjsua2")
        // We want static libraries only
        .arg("--disable-shared")
        // Disable codecs we don't need (keep G.711 for basic SIP interop)
        .arg("--disable-g7221-codec")
        .arg("--disable-ilbc-codec")
        .arg("--disable-bcg729")
        .arg("--disable-lyra")
        .arg("--disable-silk")
        .arg("--disable-opencore-amr")
        .status()
        .expect("Failed to run configure");

    if !status.success() {
        panic!("pjproject configure failed");
    }
}

fn make(pjproject_dir: &Path) {
    let nproc = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(1);

    let status = Command::new("make")
        .current_dir(pjproject_dir)
        .arg("dep")
        .status()
        .expect("Failed to run make dep");

    if !status.success() {
        panic!("pjproject make dep failed");
    }

    let status = Command::new("make")
        .current_dir(pjproject_dir)
        .arg(format!("-j{}", nproc))
        .status()
        .expect("Failed to run make");

    if !status.success() {
        panic!("pjproject make failed");
    }
}

fn gcc_system_include_paths() -> Vec<String> {
    let output = Command::new("gcc")
        .args(["-E", "-Wp,-v", "-xc", "/dev/null"])
        .output();

    let mut paths = Vec::new();
    if let Ok(output) = output {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let mut in_includes = false;
        for line in stderr.lines() {
            if line.contains("#include <...> search starts here:") {
                in_includes = true;
                continue;
            }
            if line.contains("End of search list.") {
                break;
            }
            if in_includes {
                let path = line.trim();
                if !path.is_empty() {
                    paths.push(format!("-isystem{}", path));
                }
            }
        }
    }
    paths
}

fn discover_target_name(pjproject_dir: &Path) -> String {
    // Parse build.mak to find the target name
    let build_mak = pjproject_dir.join("build.mak");
    let contents = std::fs::read_to_string(&build_mak)
        .expect("Failed to read build.mak - is pjproject configured?");

    for line in contents.lines() {
        if let Some(rest) = line.strip_prefix("export TARGET_NAME") {
            // Handle both "TARGET_NAME := value" and "TARGET_NAME=value"
            let value = rest
                .trim_start_matches(|c: char| c == ' ' || c == ':' || c == '=')
                .trim();
            if !value.is_empty() {
                return value.to_string();
            }
        }
    }

    panic!("Could not find TARGET_NAME in build.mak");
}

fn pj_build_defines(pjproject_dir: &Path) -> Vec<String> {
    let build_mak = pjproject_dir.join("build.mak");
    let contents = match std::fs::read_to_string(&build_mak) {
        Ok(contents) => contents,
        Err(_) => return Vec::new(),
    };

    let mut cflags = String::new();
    let mut collecting = false;

    for line in contents.lines() {
        if !collecting {
            if let Some((_, rest)) = line.split_once("export APP_CFLAGS :=") {
                collecting = true;
                cflags.push_str(rest.trim().trim_end_matches('\\'));
                cflags.push(' ');
                if !line.trim_end().ends_with('\\') {
                    break;
                }
            }
            continue;
        }

        cflags.push_str(line.trim().trim_end_matches('\\'));
        cflags.push(' ');
        if !line.trim_end().ends_with('\\') {
            break;
        }
    }

    cflags
        .split_whitespace()
        .filter(|token| token.starts_with("-D"))
        .map(str::to_owned)
        .collect()
}
