name: CI

on:
  push:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "pjsip-sys/pjproject"
      - "pjsip-sys/pjproject/**"
      - ".gitmodules"
  pull_request:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "pjsip-sys/pjproject"
      - "pjsip-sys/pjproject/**"
      - ".gitmodules"

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install and cache system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: >-
            binutils make gcc clang libclang-dev pkg-config protobuf-compiler
            libasound2-dev libssl-dev libopus-dev uuid-dev
          version: 1.0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --workspace --all-targets

      - name: Run tests
        run: cargo test --workspace --all-targets
